import { ExperienciaProfesional } from '../types';

/**
 * Obtener todas las experiencias profesionales (datos dummy)
 */
export const fetchExperienciasProfesionales = async (): Promise<ExperienciaProfesional[]> => {
  // Simular delay de carga
  await new Promise(resolve => setTimeout(resolve, 500));

  // Datos dummy de experiencias profesionales
  const dummyData: ExperienciaProfesional[] = [
    {
      id: 1,
      persona_id: 1,
      nombre_completo: "Carolina Pacheco Vega",
      empresa: "Clarke, Modet & C°",
      cargo: "Encargada de Calidad",
      ano_inicio: 2011,
      ano_termino: 2012,
      ano_termino_display: "2012",
      funciones: "Gestión y aseguramiento de calidad en procesos internos.",
      aptitudes: ["Gestión ambiental"],
    },
    {
      id: 2,
      persona_id: 1,
      nombre_completo: "Carolina Pacheco Vega",
      empresa: "CONAMA",
      cargo: "Profesional del Departamento de Control de la Contaminación",
      ano_inicio: 2009,
      ano_termino: 2010,
      ano_termino_display: "2010",
      funciones: "Apoyo técnico en control de la contaminación en la ex CONAMA.",
      aptitudes: ["Servicio público", "Regulación ambiental"],
    },
    {
      id: 3,
      persona_id: 5,
      nombre_completo: "Cristopher Marchant Sepúlveda",
      empresa: "MYMA",
      cargo: "Gerente de Especialidades e Innovación",
      ano_inicio: 2024,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Implementación y liderazgo de la gerencia de especialistas ambientales. Coordinación de caracterizaciones ambientales por componente y evaluación de impactos. Impulso de proyectos de innovación y geomática para productividad y eficiencia.",
      aptitudes: ["Gestión ambiental", "Liderazgo", "Innovación", "Gestión de proyectos mineros", "Representación sectorial"],
    },
    {
      id: 4,
      persona_id: 1,
      nombre_completo: "Carolina Pacheco Vega",
      empresa: "Jaime Illanes y Asociados Consultores S.A.",
      cargo: "Jefe de Proyectos",
      ano_inicio: 2018,
      ano_termino: 2021,
      ano_termino_display: "2021",
      funciones: "Coordinación de DIA, Consultas de Pertinencia, Auditorías, Prefactibilidades Ambientales y Planes de Cumplimiento ante procesos de la SMA.",
      aptitudes: ["Gestión ambiental", "Permisos ambientales", "Regulación ambiental", "Gestión de proyectos mineros", "Auditorías"],
    },
    {
      id: 5,
      persona_id: 5,
      nombre_completo: "Cristopher Marchant Sepúlveda",
      empresa: "Algoritmos (ALS)",
      cargo: "Ingeniero de Proyectos",
      ano_inicio: 2012,
      ano_termino: 2012,
      ano_termino_display: "2012",
      funciones: "Estudios de calidad del aire, meteorología, inventario de emisiones y modelación atmosférica.",
      aptitudes: ["Gestión ambiental", "Regulación ambiental"],
    },
    {
      id: 6,
      persona_id: 5,
      nombre_completo: "Cristopher Marchant Sepúlveda",
      empresa: "Codelco - RT",
      cargo: "Memorista Dirección de Medio Ambiente y Territorio",
      ano_inicio: 2012,
      ano_termino: 2013,
      ano_termino_display: "2013",
      funciones: "Trabajo de título: instrumento de planificación y gestión territorial minera (Div. Radomiro Tomic). Cartografía de riesgos, imágenes satelitales, servidor de mapas web y apoyo en gestión de calidad del aire.",
      aptitudes: ["Gestión ambiental", "Gestión minera", "Innovación"],
    },
    {
      id: 7,
      persona_id: 1,
      nombre_completo: "Carolina Pacheco Vega",
      empresa: "MYMA",
      cargo: "Gerente de Proyectos",
      ano_inicio: 2021,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Liderazgo de equipos multidisciplinarios en la ejecución de estudios de impacto ambiental y declaraciones de impacto ambiental para proyectos mineros e industriales.",
      aptitudes: ["Gestión ambiental", "Liderazgo", "Permisos ambientales", "Gestión de proyectos mineros"],
    },
    {
      id: 8,
      persona_id: 2,
      nombre_completo: "Ángel Galaz",
      empresa: "MYMA",
      cargo: "Gerente",
      ano_inicio: 2015,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Gestión administrativa, financiera y de recursos humanos de la organización.",
      aptitudes: ["Gestión administrativa", "Finanzas", "Recursos humanos"],
    },
    {
      id: 9,
      persona_id: 3,
      nombre_completo: "Christian Peralta",
      empresa: "MYMA",
      cargo: "Gerente",
      ano_inicio: 2016,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Dirección técnica de proyectos ambientales y coordinación de equipos especializados.",
      aptitudes: ["Gestión técnica", "Liderazgo", "Gestión ambiental"],
    },
    {
      id: 10,
      persona_id: 4,
      nombre_completo: "Sebastián Galaz",
      empresa: "MYMA",
      cargo: "Gerente",
      ano_inicio: 2017,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Coordinación de operaciones y gestión de proyectos en terreno.",
      aptitudes: ["Gestión de operaciones", "Liderazgo", "Proyectos en terreno"],
    },
    {
      id: 11,
      persona_id: 6,
      nombre_completo: "Luis Ayala",
      empresa: "MYMA",
      cargo: "Gerente",
      ano_inicio: 2019,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Desarrollo de negocios y relaciones con clientes en el sector minero e industrial.",
      aptitudes: ["Desarrollo de negocios", "Relaciones comerciales", "Sector minero"],
    },
    {
      id: 12,
      persona_id: 1,
      nombre_completo: "Carolina Pacheco Vega",
      empresa: "Consultora Ambiental S.A.",
      cargo: "Consultora Senior",
      ano_inicio: 2012,
      ano_termino: 2015,
      ano_termino_display: "2015",
      funciones: "Elaboración de estudios de impacto ambiental y evaluación de proyectos industriales.",
      aptitudes: ["Evaluación ambiental", "Estudios de impacto", "Consultoría"],
    },
    {
      id: 13,
      persona_id: 7,
      nombre_completo: "María González Silva",
      empresa: "Minera Los Pelambres",
      cargo: "Especialista en Gestión Ambiental",
      ano_inicio: 2020,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Supervisión de cumplimiento normativo ambiental y gestión de residuos mineros.",
      aptitudes: ["Gestión ambiental", "Normativa minera", "Residuos"],
    },
    {
      id: 14,
      persona_id: 8,
      nombre_completo: "Roberto Martínez López",
      empresa: "SMA - Superintendencia del Medio Ambiente",
      cargo: "Fiscalizador Ambiental",
      ano_inicio: 2018,
      ano_termino: 2022,
      ano_termino_display: "2022",
      funciones: "Fiscalización de cumplimiento de resoluciones de calificación ambiental y planes de seguimiento.",
      aptitudes: ["Fiscalización", "Regulación ambiental", "Servicio público"],
    },
    {
      id: 15,
      persona_id: 9,
      nombre_completo: "Ana Fernández Torres",
      empresa: "Antofagasta Minerals",
      cargo: "Coordinadora de Permisos Ambientales",
      ano_inicio: 2019,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Coordinación de procesos de obtención de permisos ambientales para proyectos mineros.",
      aptitudes: ["Permisos ambientales", "Gestión de proyectos", "Sector minero"],
    },
    {
      id: 16,
      persona_id: 10,
      nombre_completo: "Carlos Ramírez Soto",
      empresa: "Consultores Ambientales Ltda.",
      cargo: "Ingeniero de Proyectos",
      ano_inicio: 2016,
      ano_termino: 2020,
      ano_termino_display: "2020",
      funciones: "Desarrollo de caracterizaciones ambientales y planes de manejo de residuos.",
      aptitudes: ["Caracterización ambiental", "Gestión de residuos", "Ingeniería"],
    },
    {
      id: 17,
      persona_id: 11,
      nombre_completo: "Patricia Morales Rojas",
      empresa: "Codelco - División Andina",
      cargo: "Jefa de Medio Ambiente",
      ano_inicio: 2017,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Dirección del área de medio ambiente y coordinación de equipos multidisciplinarios.",
      aptitudes: ["Liderazgo", "Gestión ambiental", "Gestión minera"],
    },
    {
      id: 18,
      persona_id: 12,
      nombre_completo: "Jorge Herrera Díaz",
      empresa: "Universidad de Chile",
      cargo: "Investigador en Ciencias Ambientales",
      ano_inicio: 2015,
      ano_termino: 2018,
      ano_termino_display: "2018",
      funciones: "Investigación en calidad del aire y modelación atmosférica para proyectos académicos.",
      aptitudes: ["Investigación", "Modelación atmosférica", "Academia"],
    },
    {
      id: 19,
      persona_id: 13,
      nombre_completo: "Laura Sánchez Pérez",
      empresa: "BHP",
      cargo: "Especialista en Agua y Relaves",
      ano_inicio: 2021,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Gestión de recursos hídricos y manejo de relaves en operaciones mineras.",
      aptitudes: ["Gestión hídrica", "Relaves", "Sector minero"],
    },
    {
      id: 20,
      persona_id: 14,
      nombre_completo: "Diego Torres Muñoz",
      empresa: "SEREMI Medio Ambiente Región Metropolitana",
      cargo: "Profesional de Evaluación Ambiental",
      ano_inicio: 2014,
      ano_termino: 2017,
      ano_termino_display: "2017",
      funciones: "Evaluación técnica de proyectos sometidos al SEIA en la región metropolitana.",
      aptitudes: ["Evaluación ambiental", "SEIA", "Servicio público"],
    },
    {
      id: 21,
      persona_id: 15,
      nombre_completo: "Carmen Vega Castro",
      empresa: "Anglo American",
      cargo: "Coordinadora de Biodiversidad",
      ano_inicio: 2020,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Coordinación de programas de conservación de biodiversidad y restauración ecológica.",
      aptitudes: ["Biodiversidad", "Conservación", "Restauración ecológica"],
    },
    {
      id: 22,
      persona_id: 16,
      nombre_completo: "Fernando Castro Ruiz",
      empresa: "Consultora GeoAmbiental",
      cargo: "Geólogo Ambiental",
      ano_inicio: 2018,
      ano_termino: 2021,
      ano_termino_display: "2021",
      funciones: "Estudios geológicos ambientales y evaluación de riesgos geológicos en proyectos.",
      aptitudes: ["Geología ambiental", "Evaluación de riesgos", "Consultoría"],
    },
    {
      id: 23,
      persona_id: 17,
      nombre_completo: "Valentina López Gutiérrez",
      empresa: "Teck Resources",
      cargo: "Especialista en Calidad del Aire",
      ano_inicio: 2019,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Monitoreo y gestión de calidad del aire en operaciones mineras y modelación de emisiones.",
      aptitudes: ["Calidad del aire", "Monitoreo", "Modelación"],
    },
    {
      id: 24,
      persona_id: 18,
      nombre_completo: "Andrés Jiménez Flores",
      empresa: "Consultores Asociados S.A.",
      cargo: "Director de Proyectos Ambientales",
      ano_inicio: 2016,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Dirección de proyectos ambientales complejos y gestión de equipos técnicos.",
      aptitudes: ["Liderazgo", "Gestión de proyectos", "Dirección técnica"],
    },
    {
      id: 25,
      persona_id: 19,
      nombre_completo: "Isabel Contreras Méndez",
      empresa: "Barrick Gold",
      cargo: "Supervisora de Cumplimiento Ambiental",
      ano_inicio: 2021,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Supervisión de cumplimiento de compromisos ambientales y reportes regulatorios.",
      aptitudes: ["Cumplimiento ambiental", "Regulación", "Reportes"],
    },
    {
      id: 26,
      persona_id: 20,
      nombre_completo: "Ricardo Peña Moreno",
      empresa: "SQM",
      cargo: "Ingeniero de Procesos Ambientales",
      ano_inicio: 2017,
      ano_termino: 2023,
      ano_termino_display: "2023",
      funciones: "Optimización de procesos ambientales y reducción de impactos en operaciones industriales.",
      aptitudes: ["Procesos ambientales", "Optimización", "Industria"],
    },
    {
      id: 27,
      persona_id: 21,
      nombre_completo: "Natalia Díaz Herrera",
      empresa: "Minera Escondida",
      cargo: "Coordinadora de Relaciones Comunitarias",
      ano_inicio: 2018,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Coordinación de programas de relacionamiento comunitario y participación ciudadana.",
      aptitudes: ["Relaciones comunitarias", "Participación ciudadana", "Comunicación"],
    },
    {
      id: 28,
      persona_id: 22,
      nombre_completo: "Mauricio Silva Rojas",
      empresa: "Consultora Ambiental del Sur",
      cargo: "Especialista en EIA",
      ano_inicio: 2015,
      ano_termino: 2019,
      ano_termino_display: "2019",
      funciones: "Elaboración de estudios de impacto ambiental para proyectos de infraestructura.",
      aptitudes: ["EIA", "Estudios de impacto", "Infraestructura"],
    },
    {
      id: 29,
      persona_id: 23,
      nombre_completo: "Gabriela Muñoz Campos",
      empresa: "Freeport-McMoRan",
      cargo: "Gerente de Sostenibilidad",
      ano_inicio: 2020,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Desarrollo e implementación de estrategias de sostenibilidad corporativa.",
      aptitudes: ["Sostenibilidad", "Estrategia corporativa", "Liderazgo"],
    },
    {
      id: 30,
      persona_id: 24,
      nombre_completo: "Héctor Vargas Núñez",
      empresa: "Minera Collahuasi",
      cargo: "Jefe de Monitoreo Ambiental",
      ano_inicio: 2019,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Coordinación de programas de monitoreo ambiental y gestión de datos ambientales.",
      aptitudes: ["Monitoreo ambiental", "Gestión de datos", "Coordinación"],
    },
    {
      id: 31,
      persona_id: 25,
      nombre_completo: "Sofía Rojas Martínez",
      empresa: "Consultores en Gestión Ambiental",
      cargo: "Consultora Independiente",
      ano_inicio: 2016,
      ano_termino: null,
      ano_termino_display: "ACTUAL",
      funciones: "Consultoría especializada en gestión ambiental y asesoría en permisos ambientales.",
      aptitudes: ["Consultoría", "Permisos ambientales", "Asesoría técnica"],
    },
  ];

  return dummyData;
};

/**
 * Buscar experiencias profesionales por término de búsqueda
 */
export const searchExperienciasProfesionales = async (
  searchTerm: string
): Promise<ExperienciaProfesional[]> => {
  const allExperiencias = await fetchExperienciasProfesionales();
  
  const term = searchTerm.toLowerCase().trim();
  if (!term) {
    return allExperiencias;
  }

  // Filtrar por término de búsqueda
  return allExperiencias.filter(exp => {
    const nombreMatch = exp.nombre_completo?.toLowerCase().includes(term);
    const empresaMatch = exp.empresa?.toLowerCase().includes(term);
    const cargoMatch = exp.cargo?.toLowerCase().includes(term);
    const funcionesMatch = exp.funciones?.toLowerCase().includes(term);
    const aptitudesMatch = exp.aptitudes?.some(apt => apt.toLowerCase().includes(term));
    return nombreMatch || empresaMatch || cargoMatch || funcionesMatch || aptitudesMatch;
  });
};

